id: "448137947422654464"
name: mockplexity
model: openRouter/mistralai/mistral-7b-instruct
createdAt: 2024-05-21T15:00:12.666Z
updatedAt: 2024-06-26T10:35:07.178Z
createdBy: z1XXwZGkdCiw5KmtXXawBB1LfkzQcdmszz9
updatedBy: z1XXwZGkdCiw5KmtXXawBB1LfkzQcdmszz9
temperature: 1
topP: 1
appearance:
  primaryColor: "#2CCCE4"
